services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - .\redis\:/data
    environment:
      REDIS_PASSWORD: mdp
      REDIS_USER: user

  registry:
    image: patrikx3/p3x-redis-ui:latest
    ports:
        - "7843:7843"
    volumes:
        - /home/user/p3x-redis-ui-settings:/settings

  ghost:
    image: ghost
    ports:
      - '2368:2368'
    environment:
      database__connection__filename: mydb
    volumes:
      - .\ghost\:/var/lib/ghost/content