services:
    php:
        build:
            context: ..
            dockerfile: docker-dev/Dockerfile
        container_name: organi_game_php
        working_dir: /var/www
        volumes:
            - ../:/var/www
        depends_on:
            - db
        environment:
            SYMFONY_HOME: /tmp/.symfony5

    nginx:
        image: nginx:latest
        container_name: organi_game_nginx
        ports:
            - "8001:80"
            - "8443:443"
        volumes:
            - ../:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./certs:/etc/nginx/certs
        depends_on:
            - php

    db:
        image: mariadb:latest
        container_name: organi_game_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: organi_game_db
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3308:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: organi_game_phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - db
    node:
        image: node:22
        container_name: organi_game_node
        working_dir: /var/www
        user: "1000:1000"
        volumes:
            - ../:/var/www
        command: tail -f /dev/null

volumes:
    db_data:
